[tool.black]
line-length = 79
target-version = ['py39']
skip-string-normalization = true
exclude = '''
(
  /(
    \.git
  )/
)
'''

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]